config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: %w[index new show create] do
    resources :doses, only: %w[new create]
  end

  delete 'doses/:id', to: 'doses#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(<%= cl_image_path("vpbsgpkkkgvleyfdyp9b") %> );">
  <div class="container">
    <p>IT'S TIME FOR</p>
    <h1>Mr. Cocktail</h1>
  </div>
</div>

<div class="container w-50 mt-5 text-center">
  <h1>Cocktails</h1>
  <div class="cards"">
    <% @cocktails.each do |t| %>

      <% if t.photo.attached? %>
        <div data-aos="fade-up" data-aos-duration="<%= rand(1..30)*50 %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <%= cl_image_path t.photo.key %> )">
          <p> <%= link_to t.name.upcase, cocktail_path(t) %> </p>
        </div>
      <% else %>
        <div data-aos="fade-up" data-aos-duration="<%= rand(1..30)*50 %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.squarespace-cdn.com/content/5402e23ce4b0a7034afad3a2/1606391904322-P19CDX8914JET0X3AZES/Sloe+Gin+Negroni+with+Orange+Garnish.jpg?content-type=image%2Fjpeg)">
        <p> <%= link_to t.name.upcase, cocktail_path(t) %> </p>
        </div>
      <% end %>

    <% end %>
  </div>

  
  <%= link_to new_cocktail_path, class: "btn btn-success my-5" do  %>
      <i class="fas fa-plus special-link"></i> Add a new cocktail
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="container w-50 mt-5">
  <%= link_to cocktails_path do %>
      <i class="fas fa-undo-alt"></i> Back to list
  <% end %>

  <%= link_to cocktails_path do %>
      <span>Mr. Cocktail</span>
  <% end %>
</div>

<div class="container w-50 mt-5">
  <h1>Create a new cocktail</h1>
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.submit nil, class: "btn btn-success"%>
  <% end %>   
</div>

app/views/cocktails/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to cocktails_path do %>
    <i class="fas fa-undo-alt"></i> Back to list
  <% end %>
</div>


<div class="container justify-content-between w-50">
  
</div>


<div class="container w-50 mt-5">
  <div class="cocktail-card d-flex">

    <div class="cocktail-img">
      <% if @cocktail.photo.attached? %>
        <img src="<%= cl_image_path @cocktail.photo.key %>" alt="">
      <% else %>
        <img src="<%= image_url("old-fashioned.jpg") %>" alt="">
      <% end %>
    </div>

    <div class="cocktail-description position-relative">
      <h1 class="mb-5"><%= @cocktail.name %></h1>
      <div class="ingredients">
        <% @cocktail.doses.each do |dose| %>
          <p>
          <%= dose.description%> <%= dose.ingredient.name %>
          <%= link_to destroy_path(dose), method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
          </p>
        <% end %>
      </div>
      <p class="add-dose position-absolute"><%= link_to new_cocktail_dose_path(@cocktail) do %>
        <i class="fas fa-plus"></i> Add a new dose
      <% end %></p>
    </div>
    <div class="color-block">
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container w-50 mt-5">
  <%= link_to cocktails_path do %>
      <i class="fas fa-undo-alt"></i> Back to cocktails
  <% end %>
</div>

<div class="container w-50 mt-5">
  <h1>Create a new dose</h1>
  <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit nil, class: "btn btn-success"%>
  <% end %>   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>